baseurl = "https://getwt.io/"
languageCode = "en-us"
title = "Wellington"
theme = "github-project-landing-page"

[params]
Description = "is a project-focused tool to manage Sass and spriting"
ProfilePicture = "/images/profile.png"
enableLandingPage = false
AuthorName = "Drew"
landingPageRedirectUrl = "/install"
GithubURL = "https://github.com/wellington/wellington"

# gplp variables
AuthorURL = "http://blog.madewithdrew.com"
GithubOrg = "wellington"
GithubRepo = "wellington"

[params.Links]
Install = "/docs/install"
Docs = "/docs"
